### ISSUE TITLE
Silent renew of tokens in an IFrame fails, because the postMessage is targetted at the top window (not the parent)

### ISSUE THREAD

**Issue by devlz303** [IdentityServer/IdentityServer3.Samples#98] opened 2015-03-10 12:48 UTC
I have a situation where a web application opens a second web application in an IFrame. Both applications are SPA's that are 'secured' by an IdentityServer. I am using the oidc.js library and have configured the TokenManager to refresh the tokens silently.

In the case of the IFrame this results in the following error:
Failed to execute 'postMessage' on 'DOMWindow': The target origin provided ('https://localhost:44354') does not match the recipient window's origin ('https://localhost:44347').oidc.js:1116 TokenManager.processTokenCallbackSilent

The processTokenCallbackSilent function is using window.top as the target window to post the hash to.
Now in case of the IFrame this is not working, because the location of the top.window is the other web application. This problem can be fixed by replacing window.top by window.parent in TokenManager.prototype.processTokenCallbackSilent, because it's always the parent window that initiates the token refresh.

Is it possible to change this code?

**Comment by brockallen** [comment] 2015-03-11 00:49
No -- that's a security threat. How can the inner window be sure the containing window is safe to communicate with?

**Comment by devlz303** [comment] 2015-03-11 08:52
Are you sure this is a security threat? I don't see it..
It's the targetOrigin parameter in the postMessage call that makes sure the origin of the target window is the same origin as the origin of the inner window. The code in the oidc.js is preventing communication with windows that do not have the same origin as the inner window by specifying this targetOrigin parameter.

Right now, the code is preventing communication with the top window and that's correct because my top window is not the same origin as the inner window. But I want to communicate with the inner window's parent, which is the same origin.

Let me ask you this question: Wouldn't it be strange if the inner window would communicate with another window than it's parent? The code in the oidc.js id creating a child window, so the child should (in my opinion) only communicate with it's parent. The targetOrigin parameter is there to make sure this parent window is from the same origin.

I would like to know what's wrong in my thinking..

**Comment by brockallen** [comment] 2015-03-13 01:15
Ok, I re-read your post... I think I misunderstood -- the issue is that the loaded iframe just needs to post back to its parent, not the the top -- is that right?

**Comment by devlz303** [comment] 2015-03-13 07:51
Yes, that's correct.

The patent is the one that created the child (not the grandparent :)).
So the child should always talk to it's parent (using postMessage).
And the targetOrigin parameter is used to prevent to post the message to someone elses parent (not the same origin).

**Comment by devlz303** [comment] 2015-03-13 11:11
I have made a pull request for this issue.

**Comment by brockallen** [comment] 2015-03-16 15:19
This was fixed on dev, and then merged to master.

**Closed by brockallen** 2015-03-16 15:19 UTC
Labels: question
